apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base-chart.fullname" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    secrets.infisical.com/auto-reload: "true"
  labels:
    {{- include "base-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "base-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or .Values.istio.enabled .Values.podAnnotations }}
      annotations:
        {{- if .Values.istio.enabled }}
        sidecar.istio.io/rewriteAppHTTPProbers: {{ .Values.istio.sidecar.rewriteAppHTTPProbers | quote }}
        sidecar.istio.io/proxyCPU: {{ .Values.istio.sidecar.proxyCPU | quote }}
        sidecar.istio.io/proxyCPULimit: {{ .Values.istio.sidecar.proxyCPULimit | quote }}
        sidecar.istio.io/proxyMemory: {{ .Values.istio.sidecar.proxyMemory | quote }}
        sidecar.istio.io/proxyMemoryLimit: {{ .Values.istio.sidecar.proxyMemoryLimit | quote }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "base-chart.labels" . | nindent 8 }}
        {{- if .Values.istio.enabled }}
        sidecar.istio.io/inject: "true"
        {{- end }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "base-chart.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.envFrom .Values.infisicalSecret.enabled }}
          envFrom:
            {{- if .Values.infisicalSecret.enabled }}
            - secretRef:
                name: {{ .Values.infisicalSecret.secretName | default .Values.global.secretName }}
            {{- end }}
            {{- with .Values.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if or .Values.env .Values.valkey.enabled .Values.rabbitmq.enabled }}
          env:
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.valkey.enabled }}
            - name: REDIS_HOST
              value: {{ include "base-chart.fullname" . }}-valkey
            - name: REDIS_PORT
              value: "6379"
            {{- end }}
            {{- if .Values.rabbitmq.enabled }}
            - name: RABBITMQ_HOST
              value: {{ include "base-chart.fullname" . }}-rabbitmq
            - name: RABBITMQ_PORT
              value: {{ .Values.rabbitmq.service.amqpPort | quote }}
            - name: RABBITMQ_USER
              value: {{ .Release.Name }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- if .Values.livenessProbe.httpGet }}
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path | default "/" }}
              port: {{ .Values.livenessProbe.httpGet.port | default .Values.service.containerPort }}
            {{- else }}
            {{- toYaml .Values.livenessProbe | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- if .Values.readinessProbe.httpGet }}
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path | default "/" }}
              port: {{ .Values.readinessProbe.httpGet.port | default .Values.service.containerPort }}
            {{- else }}
            {{- toYaml .Values.readinessProbe | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
