{{- if .Values.infisicalSecret.enabled }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ .Values.infisicalSecret.secretName | required "infisicalSecret.secretName is required" }}
  labels:
    {{- include "base-chart.labels" . | nindent 4 }}
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: {{ .Values.infisicalSecret.projectSlug | required "infisicalSecret.projectSlug is required" }}
        envSlug: {{ .Values.infisicalSecret.envSlug | required "infisicalSecret.envSlug is required" }}
        secretsPath: {{ .Values.infisicalSecret.secretsPath | default "/" | quote }}
        recursive: {{ .Values.infisicalSecret.recursive | default true }}
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: {{ .Values.infisicalSecret.secretName }}
      secretNamespace: {{ .Release.Namespace }}
      creationPolicy: {{ .Values.infisicalSecret.creationPolicy | default "Orphan" }}
      template:
        includeAllSecrets: true
{{- end }}
